### ISSUE TITLE
Allow flash-friendly requests using query parameters

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-registry#6]
2 issues with flashplayer:
- it only supports POST and GET.
- if requests status isn't `success`, it's not possible to read the response body.

Registry could perform flash friendly requests conversion:

Converts the following input:

`POST xxxx?method=delete` to `DELETE xxxx`
POST xxxx?method=put`to`PUT xxxx`

Converts non 200 return status to JSON with status 200.

**Comment by elmigranto** [comment]
Something like this should probably work: https://github.com/expressjs/method-override (maybe we can even use it just by `server.use` call).

**Comment by elmigranto** [comment]
What about HTTP Responses with non 2xx codes? Like 403 and such?

**Comment by j3k0** [comment]
In flashplayer, if response has non 2xx status, the body is not accessible (so we can't read the api error code or message). The solution to address that, send errors with 2xx status and with body `{ "httpStatus": 403, "httpBody": actualBody }`

The registry is proxying request to underlying services, so we can make it smarter, check for `?ff=1` in url parameter, convert input request and output response to and from the targeted microservice.
